[project]
name = "desktop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ryo Igarashi", email = "n33t5hin@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ansible>=14.2.0",
]

[project.scripts]
desktop = "desktop:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
