---
- name: "Install AUR package: {{ aur_name }}"
  vars:
    aur_base: "{{ ansible_facts['user_dir'] }}/.cache/aur"
    aur_workdir: "{{ aur_base }}/{{ aur_name }}"
  block:
    - name: "Ensure AUR is cloned"
      ansible.builtin.git:
        repo: https://aur.archlinux.org/{{ aur_name }}.git
        dest: "{{ aur_workdir }}"
        version: "{{ aur_version }}"

    - name: "Ensure AUR is registered to a variable"
      register: packagelist
      ansible.builtin.shell:
        chdir: "{{ aur_workdir }}"
        # TODO: vscode-langservers-extracted が debug を出力するんだけど生成はされていない。上流のミス？
        cmd: |
          set -o pipefail
          makepkg --packagelist | awk '! /-debug-/'
      changed_when: false
      check_mode: false

    - name: "Ensure AUR is built"
      ansible.builtin.command:
        chdir: "{{ aur_workdir }}"
        cmd: "makepkg"
        creates: "{{ packagelist.stdout_lines[0] }}"

    - name: "Ensure AUR is installed"
      become: true
      community.general.pacman:
        name: "{{ packagelist.stdout_lines }}"
