---
- name: Prepare Desktop
  hosts: localhost
  tasks:
    ################################################################################
    # 環境変数
    ################################################################################
    - name: Ensure environment is copied
      become: true
      ansible.builtin.copy:
        src: environment
        dest: /etc/environment
        mode: "0644"

    - name: Ensure locales are enabled
      become: true
      community.general.locale_gen:
        name:
        - "en_US.UTF-8"

    ################################################################################
    # ネットワークまわり
    ################################################################################
    - name: Ensure networkmanager is prepared
      become: true
      block:
        - name: Ensure networkmanager is installed
          community.general.pacman:
            name: networkmanager

        - name: Ensure networkmanager is enabled
          ansible.builtin.service:
            name: NetworkManager 
            enabled: true
            state: started

    ################################################################################
    # ユーザーを作る
    ################################################################################
    - name: Ensure user is prepared
      become: true
      block:
        - name: Ensure sudo is installed
          community.general.pacman:
            name: sudo

        - name: Ensure user is created
          ansible.builtin.user:
            name: "{{ user_name }}"
            password: "{{ user_password }}" 
            groups: wheel
            append: yes
            update_password: on_create

        - name: Ensure wheel group can sudo
          community.general.sudoers:
            name: wheel
            group: wheel
            runas: ALL:ALL
            commands: ALL
            nopassword: false
    
    ################################################################################
    # 開発環境のセットアップ
    ################################################################################
    - name: Ensure Neovim and related packages are installed
      become: true
      community.general.pacman:
        name:
          - direnv
          - gcc
          - ghq
          - git
          - lazygit
          - less
          - neovim
          - tree-sitter-cli

    ################################################################################
    # Bluetooth のセットアップ
    ################################################################################
    - name: Ensure Bluetooth is prepared
      become: true
      block:
        - name: Ensure Bluetooth related packages are installed
          community.general.pacman:
            name:
              - bluez
              - bluez-utils

        - name: Ensure bluetooth is enabled
          ansible.builtin.service:
            name: bluetooth
            enabled: true
            state: started

    ################################################################################
    # GUI のセットアップ
    ################################################################################
    - name: Ensure GNOME and related packages are installed
      become: true
      community.general.pacman:
        name:
        - alacritty
        - discord
        - firefox
        - gnome

    ################################################################################
    # AUR のインストール
    ################################################################################
    - name: Ensure 1Password is installed
      ansible.builtin.include_tasks: aur.yml
      vars:
        aur_name: 1password
        aur_version: d991324ae2605a3142318cd33fe3d7da6a9f98eb

    - name: Ensure ibus-mozc is installed
      ansible.builtin.include_tasks: aur.yml
      vars:
        aur_name: ibus-mozc
        aur_version: 25a9f3c5a69617b04330c0efe8fc6cb2c98870fc 

    - name: Ensure mozc is installed
      ansible.builtin.include_tasks: aur.yml
      vars:
        aur_name: mozc
        aur_version: 53a13d01af98e3e08f35c49b441cc0fafdaea86f
