---
- name: Prepare Desktop
  hosts: localhost

  handlers:
    - name: Restart Xremap
      ansible.builtin.service:
        name: xremap
        scope: user
        state: restarted
        daemon_reload: true

    - name: Restart bluetooth
      become: true
      ansible.builtin.service:
        name: bluetooth
        state: restarted

    - name: Run fc-cache
      become: true
      changed_when: false
      ansible.builtin.command:
        cmd: "fc-cache -fv"

    - name: Restart avahi
      become: true
      ansible.builtin.service:
        name: avahi-daemon
        state: restarted

  tasks:
    ################################################################################
    # 環境変数
    ################################################################################
    - name: Ensure environment is copied
      become: true
      ansible.builtin.copy:
        src: environment
        dest: /etc/environment
        mode: "0644"

    - name: Ensure locales are enabled
      become: true
      community.general.locale_gen:
        name:
          - "en_US.UTF-8"

    ################################################################################
    # ネットワークまわり
    ################################################################################
    - name: Ensure networkmanager is prepared
      become: true
      block:
        - name: Ensure networkmanager is installed
          community.general.pacman:
            name: networkmanager

        - name: Ensure networkmanager is enabled
          ansible.builtin.service:
            name: NetworkManager
            enabled: true
            state: started

    - name: Ensure mDNS is ready
      become: true
      notify: Restart avahi
      block:
        - name: Ensure avahi and nss-mdns is installed
          community.general.pacman:
            name:
              - avahi
              - nss-mdns

        - name: Ensure mDNS is set to nsswitch
          ansible.builtin.lineinfile:
            path: /etc/nsswitch.conf
            regexp: "^hosts:"
            line: "hosts: mymachines mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] files myhostname dns"

        - name: Ensure avahi-daemon is enabled
          ansible.builtin.service:
            name: avahi-daemon
            enabled: true
            state: started

    ################################################################################
    # ユーザーを作る
    ################################################################################
    - name: Ensure user is prepared
      become: true
      block:
        - name: Ensure sudo is installed
          community.general.pacman:
            name: sudo

        - name: Ensure user is created
          ansible.builtin.user:
            name: "{{ user_name }}"
            password: "{{ user_password }}"
            update_password: on_create
            shell: /usr/bin/zsh
            groups:
              - wheel
              - input
            append: true

        - name: Ensure wheel group can sudo
          community.general.sudoers:
            name: wheel
            group: wheel
            runas: ALL:ALL
            commands: ALL
            nopassword: false

        - name: Ensure openssh key is generated
          community.crypto.openssh_keypair:
            path: "{{ ansible_facts['user_dir'] }}/.ssh/id_ed25519"
            type: ed25519
            backend: opensshbin

    ################################################################################
    # 開発環境のセットアップ
    ################################################################################
    - name: Ensure Neovim and related packages are installed
      become: true
      community.general.pacman:
        name:
          - direnv
          - fastfetch
          - fzf
          - gcc
          - ghq
          - git
          - github-cli
          - glow
          - jq
          - lazygit
          - less
          - lua-language-server
          - neovim
          - nodejs
          - npm
          - ripgrep
          - rust
          - tmux
          - tree-sitter-cli
          - typescript-language-server
          - zsh
          - zsh-autosuggestions
          - zsh-completions
          - zsh-syntax-highlighting

    ################################################################################
    # dotfiles のセットアップ
    ################################################################################
    - name: Ensure dotfiles is up
      become: true
      vars:
        dotfiles_dir: "{{ ansible_facts['user_dir'] }}/dotfiles"
      block:
        - name: Ensure dotfiles is cloned # noqa latest
          ansible.builtin.git:
            repo: https://github.com/neet/dotfiles
            dest: "{{ dotfiles_dir }}"

        - name: Ensure setup ran
          changed_when: false
          ansible.builtin.command:
            chdir: "{{ dotfiles_dir }}"
            cmd: "./setup.sh"

    ################################################################################
    # Bluetooth のセットアップ
    ################################################################################
    - name: Ensure Bluetooth is prepared
      become: true
      notify: Restart bluetooth
      block:
        - name: Ensure Bluetooth related packages are installed
          community.general.pacman:
            name:
              - bluez
              - bluez-utils

        - name: Ensure bluetooth is enabled
          ansible.builtin.service:
            name: bluetooth
            enabled: true
            state: started

    ################################################################################
    # GUI のセットアップ
    ################################################################################
    - name: Ensure GNOME packages are prepared
      block:
        - name: Ensure GNOME is installed
          become: true
          community.general.pacman:
            name:
              # GNOME グループに入っているやつ
              - gdm
              - gnome-color-manager
              - gnome-control-center
              - gnome-font-viewer
              - gnome-keyring
              - gnome-logs
              - gnome-menus
              - gnome-remote-desktop
              - gnome-session
              - gnome-settings-daemon
              - gnome-shell
              - gnome-system-monitor
              - gnome-user-docs
              - gst-thumbnailers
              - gvfs
              - gvfs-dnssd
              - gvfs-smb
              - gvfs-wsdd
              - loupe
              - nautilus
              - orca
              - showtime
              - sushi
              - xdg-desktop-portal-gnome
              - xdg-user-dirs-gtk
              - yelp

        - name: Ensure gdm is enabled
          ansible.builtin.service:
            name: gdm
            enabled: true
            state: started

        - name: Ensure GNOME related packages are installed
          become: true
          community.general.pacman:
            name:
              # Firefox から GNOME extension を入れる
              - gnome-browser-connector
              # Neovim から Wayland のクリップボードにアクセスするために必要
              # https://neovim.io/doc/user/provider/#provider-clipboard
              - wl-clipboard
              # showtime で H.264 を再生するのに必要
              - gst-libav
              # dconf (gsettings の低レベル API)
              - dconf-editor

        - name: Ensure GUI apps are installed
          become: true
          community.general.pacman:
            name:
              - alacritty
              - anki
              - discord
              - firefox
              - solaar
              - noto-fonts-cjk
              - ttf-jetbrains-mono-nerd

        - name: Ensure fontconfig is set
          become: true
          notify: Run fc-cache
          ansible.builtin.copy:
            src: font.conf
            dest: /etc/fonts/local.conf
            mode: "0644"

    ################################################################################
    # AUR のインストール
    ################################################################################
    - name: Ensure AUR packages are prepared
      block:
        # makepkg に become 付けたら怒られるのでどうすればいいのやら。
        - name: Ensure AUR packages are installed
          ansible.builtin.include_tasks: tasks/aur.yml
          vars:
            aur_name: "{{ item.key }}"
            aur_version: "{{ item.value }}"
          with_dict:
            1password: d991324ae2605a3142318cd33fe3d7da6a9f98eb
            claude-code: c228df23638624076be486c55c697b06e6d1d1d7
            ibus-mozc: 25a9f3c5a69617b04330c0efe8fc6cb2c98870fc
            mozc: 53a13d01af98e3e08f35c49b441cc0fafdaea86f
            slack-desktop: 1275d6840eb7998cd94ae5d1ea7687c2b219f6e6
            vscode-langservers-extracted: 6a5dd717ba64ba85fbaed3f33e34f3184a127b44
            zsh-pure-prompt: 6b8c56e594d4a3c53c9bc68d08e1fa64c8fe2648

    ################################################################################
    # Xremap のインストール
    # https://github.com/xremap/xremap/blob/master/doc/running_without_sudo.md
    ################################################################################
    - name: Ensure Xremap is prepared
      notify: Restart Xremap
      block:
        - name: Ensure Xremap is installed
          community.general.cargo:
            name: xremap
            version: 0.10.7
            features: [gnome]

        - name: Ensure Xremap config is copied
          ansible.builtin.copy:
            src: xremap.yaml
            dest: "{{ ansible_facts['user_dir'] }}/.config/xremap.yaml"
            mode: "0644"

        - name: Ensure input group can create output devices
          become: true
          ansible.builtin.copy:
            src: 99-input.rules
            dest: /etc/udev/rules.d/99-input.rules
            mode: "0644"

        - name: Ensure Xremap service exists
          ansible.builtin.copy:
            src: xremap.service
            dest: "{{ ansible_facts['user_dir'] }}/.config/systemd/user/xremap.service"
            mode: "0644"

        - name: Ensure Xremap is enabled
          ansible.builtin.service:
            name: xremap
            scope: user
            enabled: true
            state: started
