---
- name: Prepare Desktop
  hosts: localhost
  become: true
  tasks:
    ################################################################################
    # 有線ネットワークまわり
    ################################################################################
    - name: Ensure wired-network config is set
      ansible.builtin.copy:
        src: 20-wired.network
        dest: /etc/systemd/network/20-wired.network
        mode: "0644"

    - name: Ensure wireless-network config is set
      ansible.builtin.copy:
        src: 25-wireless.network
        dest: /etc/systemd/network/25-wireless.network
        mode: "0644"

    - name: Ensure systemd-networkd is enabled
      ansible.builtin.service:
        name: systemd-resolved
        enabled: true
        state: started

    ################################################################################
    # DNS まわり
    ################################################################################
    - name: Ensure resolve config is linked
      ansible.builtin.file:
        src: /run/systemd/resolve/stub-resolv.conf
        dest: /etc/resolv.conf
        state: link

    - name: Ensure wired-network config is set
      ansible.builtin.copy:
        src: 20-wired.network
        dest: /etc/systemd/network/20-wired.network
        mode: "0644"

    - name: Ensure systemd-resolved is enabled
      ansible.builtin.service:
        name: systemd-resolved
        enabled: true
        state: started

    ################################################################################
    # 無線ネットワークまわり
    # WiFiへの接続自体は自分でやったほうがよいか
    ################################################################################
    - name: Ensure iwd is installed
      community.general.pacman:
        name: iwd

    ################################################################################
    # ユーザーを作る
    ################################################################################
    - name: Ensure sudo is installed
      community.general.pacman:
        name: sudo

    # TODO: 本来はここで passwd neet している

    - name: Ensure user neet is created
      ansible.builtin.user:
        name: neet
        groups: wheel
        append: yes

    # TODO: 本来はここで visudo している
    # https://docs.ansible.com/projects/ansible/latest/collections/community/general/sudoers_module.html
    
    # TODO: ここの手順2をやる
    # https://wiki.archlinux.jp/index.php/%E3%83%AD%E3%83%BC%E3%82%AB%E3%83%AA%E3%82%BC%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3#%E3%83%AD%E3%82%B1%E3%83%BC%E3%83%AB

    ################################################################################
    # 開発環境のセットアップ
    ################################################################################
    - name: Ensure Neovim and related packages are installed
      community.general.pacman:
        name:
          - neovim
          - gcc
          - direnv
          - tree-sitter-cli

    ################################################################################
    # Bluetooth のセットアップ
    ################################################################################
    - name: Ensure Bluetooth related packages are installed
      community.general.pacman:
        name:
          - bluez
          - bluez-utils

    - name: Ensure bluetooth is enabled
      ansible.builtin.service:
        name: bluetooth
        enabled: true
        state: started

    ################################################################################
    # GUI のセットアップ
    ################################################################################
    - name: Ensure GNOME is installed
      community.general.pacman:
        name: gnome
